sudo: true
dist: trusty
language: node_js
cache:
  directories:
  - node
  - node_modules
node_js:
  - 6.9
services:
  - mongodb
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - curl https://install.meteor.com | /bin/sh
  - cd api
  - meteor npm install
  - cd ..
  - npm install

before_script:
  - npm run meteor-client:bundle -- --url=$METEOR_API_URL

script:
  - npm run build -- --prod

after_script:
  - cd api
  - npm run test:spacejam
  - cd ..
  - npm test -- --watch false
  - npm test -- --code-coverage --single-run
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
